name: Keep Chatbot Awake

on:
  schedule:
    - cron: "*/10 * * * *"  # runs every 10 minutes
  workflow_dispatch:

jobs:
  ping_render_chatbot:
    runs-on: ubuntu-latest
    steps:
      - name: Send warmup ping to Render chatbot
        run: |
          curl -s -o /dev/null -w "HTTP: %{http_code}\n" https://pranav-chatbot-proxy.onrender.com/api/chat \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data '{"input": "Hi"}'
